/*
* generated by Xtext
*/
package org.xtext.example.rmodp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.rmodp.services.RmOdpGrammarAccess;

public class RmOdpParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RmOdpGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.rmodp.parser.antlr.internal.InternalRmOdpParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.rmodp.parser.antlr.internal.InternalRmOdpParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public RmOdpGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RmOdpGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
