/*
 * generated by Xtext
 */
package org.xtext.example.rmodp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RmOdpRuntimeModule extends org.xtext.example.rmodp.AbstractRmOdpRuntimeModule {

}
