/*
* generated by Xtext
*/
package org.xtext.example.rmodp.ui.contentassist;

import org.xtext.example.rmodp.ui.contentassist.AbstractRmOdpProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RmOdpProposalProvider extends AbstractRmOdpProposalProvider {

}
