/*
 * generated by Xtext
 */
package org.xtext.example.rmodp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RmOdpUiModule extends org.xtext.example.rmodp.ui.AbstractRmOdpUiModule {
	public RmOdpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
